name: Cleanup Preview (Vercel)

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup:
    # Secrets aren't available for forks. Skip gracefully in that case.
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest

    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          miss=0
          for k in VERCEL_TOKEN VERCEL_ORG_ID VERCEL_PROJECT_ID; do
            if [ -z "${!k}" ]; then echo "❌ Missing secret: $k"; miss=1; fi
          done
          [ "$miss" -eq 0 ] || { echo "Add missing secrets in repo settings"; exit 0; }

      - name: Locate preview URL from sticky PR comment
        id: find_url
        uses: actions/github-script@v7
        with:
          script: |
            const header = '<!-- vercel-preview-url -->';
            const number = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number: number });
            const c = comments.find(cm => cm.body && cm.body.includes(header));
            if (!c) {
              core.info('No sticky preview comment found; nothing to clean.');
              core.setOutput('url', '');
              return;
            }
            const m = c.body.match(/https?:\/\/\S+/);
            core.setOutput('url', m ? m[0] : '');
            core.setOutput('comment_id', String(c.id));

      - name: Short-circuit if no URL
        if: ${{ steps.find_url.outputs.url == '' }}
        run: echo "No preview URL found; skipping removal."

      - name: Remove Vercel preview deployment
        if: ${{ steps.find_url.outputs.url != '' }}
        id: remove
        run: |
          DEPLOY_URL='${{ steps.find_url.outputs.url }}'
          # Vercel accepts full URL or the subdomain; pass the URL directly.
          echo "Deleting preview deployment: $DEPLOY_URL"
          npx vercel rm "$DEPLOY_URL" --safe --yes --token="$VERCEL_TOKEN"

      - name: Update sticky PR comment (marked as cleaned up)
        if: ${{ steps.find_url.outputs.comment_id != '' }}
        uses: actions/github-script@v7
        with:
          script: |
            const header = '<!-- vercel-preview-url -->';
            const url = core.getInput('url');
            const { owner, repo } = context.repo;
            const comment_id = Number(core.getInput('comment_id'));

            const cleaned = `🧹 **Preview deleted** (PR closed)\n\n${url ? `~${url}~` : ''}`;
            await github.rest.issues.updateComment({
              owner, repo, comment_id,
              body: `${header}\n${cleaned}`
            });
          inputs: |
            url: ${{ steps.find_url.outputs.url }}
            comment_id: ${{ steps.find_url.outputs.comment_id }}
